// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrRJt7G-mTCF6i0dSTcEuMgZE2SPxcTdU',
    appId: '1:554727876397:web:190afd760808f8d78855a4',
    messagingSenderId: '554727876397',
    projectId: 'task-manager-analytics',
    authDomain: 'task-manager-analytics.firebaseapp.com',
    storageBucket: 'task-manager-analytics.firebasestorage.app',
    measurementId: 'G-PKCFXBR4LY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDW79TxxeV5DKKNvWpytphdiDFL8pWJdpU',
    appId: '1:554727876397:android:dbbd16e6adb085e38855a4',
    messagingSenderId: '554727876397',
    projectId: 'task-manager-analytics',
    storageBucket: 'task-manager-analytics.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWes9yguK1jgMP7_OnPJA1BzayP9ywfNI',
    appId: '1:554727876397:ios:64a02eb457dded298855a4',
    messagingSenderId: '554727876397',
    projectId: 'task-manager-analytics',
    storageBucket: 'task-manager-analytics.firebasestorage.app',
    iosBundleId: 'com.example.studentWorkTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWes9yguK1jgMP7_OnPJA1BzayP9ywfNI',
    appId: '1:554727876397:ios:64a02eb457dded298855a4',
    messagingSenderId: '554727876397',
    projectId: 'task-manager-analytics',
    storageBucket: 'task-manager-analytics.firebasestorage.app',
    iosBundleId: 'com.example.studentWorkTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBrRJt7G-mTCF6i0dSTcEuMgZE2SPxcTdU',
    appId: '1:554727876397:web:b266dc328c22ffaf8855a4',
    messagingSenderId: '554727876397',
    projectId: 'task-manager-analytics',
    authDomain: 'task-manager-analytics.firebaseapp.com',
    storageBucket: 'task-manager-analytics.firebasestorage.app',
    measurementId: 'G-ZEG3XGPG83',
  );
}
